function [] = pathConfig()
% Add some directories, where all the functions are
%   PK 21/03/2019

addpath('./Config/',...
    './PTBTools/',...
    './Conversion/',...
    './Eyelink/',...
    './Stim/',...
	'./GammaCalib/',...
    './data/',...
    './Analyses1/',...
    './Trial/');

end

